# -*- coding: utf-8 -*-
"""Copy of lecture4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bSqw4O8ISj_o2wRNx0drSZKQTDr9Epc7
"""

for i in 'python':
  print(i)

option=input("CHoose any option")
while (option!="quit"):
    if (option.upper()=="START"):
     print("CAR started")
     break
    elif (option.upper()=="STOP"):
     print("CAR stopped")
     break
    elif (option.upper()=="HELP"):
     print(
         '''
         start - to start the car
         stop - to stop the car
         quit -  quit
         '''
     )
     break
    else:
     print("CHoose any other option THis is invalid")